// src/components/BaseButton.svelte
<div
  class="baseBtn stylizedBtn"
  class:active="{concurrentPlays !== 0}"
  class:baseBtnInList
  class:pending
  class:testHoverWidth
  style="min-width: {minWidth}"
  on:click="{playSound}"
  bind:this="{self}"
  tabindex="0"
>
  {localizedName}
</div>

<script lang="ts">
  import { getContext, onMount } from 'svelte'
  import { format, locale } from 'svelte-i18n'
  import type { ErrorFormatter, Sound } from '../types'
  import siteConfig from '../config'
  import type CentralPlayer from './centralPlayer'
  import { ln } from '../utils/i18n'
  const assetBasePath = siteConfig.assets_path

  // Props
  export let item: Sound
  export let baseBtnInList: boolean = true
  let playerCtx: CentralPlayer
  let concurrentPlays = 0
  let pending = false
  let testHoverWidth: boolean = false
  let self
  let minWidth = '0px'

  $: localizedName = ln($locale, item)

  // Methods
  function selectFile(): string {
    if (Array.isArray(item.file)) {
      return item.file[Math.floor(Math.random() * item.file.length)]
    } else {
      return item.file
    }
  }

  function scanHoverWidth() {
    minWidth = '0px'
    testHoverWidth = true
    requestAnimationFrame(() => {
      const width = self.offsetWidth
      minWidth = String(width - 16 + 'px')
      testHoverWidth = false
    })
  }

  export function playSound() {
    pending = true
    const audio = playerCtx.addAudio(assetBasePath + selectFile())
    const playTimeout = setTimeout(() => {
      window?.errorFormatter(
        $format('Voices are still loading. Please be patient...')
      )
    }, 1500)
    audio.addEventListener('play', () => {
      concurrentPlays++
    })
    audio.addEventListener('pause', () => {
      concurrentPlays--
    })
    audio
      .play()
      .then(() => {
        pending = false
        clearTimeout(playTimeout)
      })
      .catch((e) => {
        window?.errorFormatter(
          $format('Error in the playback:') + ' ' + String(e)
        )
      })
  }

  onMount(() => {
    playerCtx = getContext('player')
    if (baseBtnInList) {
      scanHoverWidth()
      window.addEventListener('languagechange', scanHoverWidth)
    }
  })
</script>

<style lang="scss">
  @import '../styles/BaseButton.scss';
  @import '../styles/common.scss';

  .pending {
    opacity: 0.8;
  }
</style>

// src/components/BaseButton.vue
<template>
  <div
    @click="play"
    ref="self"
    :class="{
      playingBtn: playLayer > 0,
      testHoverWidth,
      pending: pendingNetwork,
    }"
    :style="{
      minWidth,
    }"
    tabindex="0"
  >
    {{ localizedName }}
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from "vue-property-decorator";
import { Sound } from "../types";

@Component
export default class BaseButton extends Vue {
  @Prop() private item!: Sound;
  @Prop() private noclickplay!: boolean;
  private playLayer = 0;
  private pendingNetwork = false;
  private testHoverWidth = false;
  private minWidth = "0px";
  private mounted() {
    this.testHoverWidth = true;
    this.$nextTick(() => {
      const width = (this.$refs.self as HTMLElement).offsetWidth;
      this.minWidth = String(width - 16 + "px");
      this.testHoverWidth = false;
    });
  }
  get localizedName() {
    return (
      (this?.item.name_l10n || {})[this.$i18n.locale] || this?.item.name || ""
    );
  }

  public emitError(e: any) {
    this.$emit(
      "error",
      this.$t("Error in sound playing:").toString() +
        e.toString() +
        "\n" +
        this.$t("We've known about it and will work on it soon.").toString()
    );
  }

  public play() {
    try {
      this.playHandler();
    } catch (e) {
      this.emitError(e);
      throw e;
    }
  }

  private playHandler() {
    if (this.noclickplay) return;
    if (!this.item) {
      return;
    }
    let audioFilename;
    if (typeof this.item.file === "string") {
      audioFilename = this.item.file;
    } else {
      audioFilename = this.item.file[
        Math.floor(Math.random() * this.item.file.length)
      ];
    }
    this.pendingNetwork = true;
    let audio: HTMLAudioElement | null = null;
    let playPromise;
    const notifyUserOfLongLoadingTime = setTimeout(() => {
      this.$emit(
        "error",
        this.$t("Voices are still loading. Please be patient...")
      );
    }, 1500);
    try {
      audio = this.$status.player.addAudio(`assets/${audioFilename}`);
      this.$status.player.stopAllWhenNonMultiPlay();
      playPromise = audio?.play();
    } catch (err) {
      this.$status.player.stopAllWhenNonMultiPlay();
      playPromise = audio?.play();
    }

    if (playPromise !== undefined) {
      playPromise
        .then(() => {
          clearTimeout(notifyUserOfLongLoadingTime);
          this.pendingNetwork = false;
          this.playLayer += 1;
          if (this.playLayer === 1) {
            this.$emit("started");
          }
        })
        .catch((e) => {
          this.emitError(e);
          throw e;
        });
    }

    audio?.addEventListener("pause", () => {
      this.playLayer -= 1;
      if (this.playLayer === 0) {
        this.$emit("stopped");
      }
    });
  }
}
</script>

<style lang="scss" scoped>
.pending {
  opacity: 0.8;
}
</style>
